apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-orchestrator-data-pvc
  labels:
    app: ai-orchestrator-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard