apiVersion: v1
kind: Secret
metadata:
  name: ai-orchestrator-secrets
  labels:
    app: ai-orchestrator-backend
type: Opaque
data:
  # Base64 encoded values - these should be generated securely
  database_url: cG9zdGdyZXM6Ly91c2VyOnBhc3NAZGJfaG9zdDo1NDMyL2RiX25hbWU=  # postgres://user:pass@db_host:5432/db_name
  jwt_secret: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl  # your-jwt-secret-key-here
  redis_password: eW91ci1yZWRpcy1wYXNzd29yZA==  # your-redis-password
  encryption_key: eW91ci0yNTYtYml0LWVuY3J5cHRpb24ta2V5  # your-256-bit-encryption-key
  api_key: eW91ci1hcGkta2V5LWZvci1leHRlcm5hbC1zZXJ2aWNlcw==  # your-api-key-for-external-services