# Development Monitoring Configuration
# Lightweight monitoring setup for development environment

[production_monitoring]
# Health monitoring settings (less frequent in dev)
health_check_interval_seconds = 60
performance_collection_interval_seconds = 30
metrics_retention_hours = 24  # 1 day
alert_evaluation_interval_seconds = 120
dashboard_refresh_interval_seconds = 60

# Prometheus exporter settings
enable_prometheus_exporter = true
prometheus_port = 9091

# Grafana integration (optional in dev)
enable_grafana_integration = false
grafana_url = "http://localhost:3000"

# Notification channels (console only in dev)
[[production_monitoring.notification_channels]]
channel_type = "console"
enabled = true
severity_filter = ["info", "warning", "critical"]

# Alerting thresholds (more lenient in dev)
[production_monitoring.alerting_thresholds]
agent_health_critical_threshold = 0.3
agent_health_warning_threshold = 0.5
system_cpu_critical = 95.0
system_cpu_warning = 85.0
system_memory_critical = 98.0
system_memory_warning = 90.0
task_failure_rate_critical = 50.0
task_failure_rate_warning = 20.0
response_time_critical_ms = 10000.0
response_time_warning_ms = 2000.0
error_rate_critical_per_minute = 20.0
error_rate_warning_per_minute = 5.0
agent_utilization_low_threshold = 20.0
throughput_drop_threshold_percent = 30.0

# Business metrics configuration
[production_monitoring.business_metrics_config]
enable_business_metrics = true
task_completion_target_percentage = 90.0
agent_utilization_target_percentage = 70.0
system_uptime_target_percentage = 99.0
customer_satisfaction_target_score = 4.0

# Intelligent alerting configuration (simplified in dev)
[intelligent_alerting]
max_alert_history = 1000
adaptive_learning_enabled = false
predictive_alerting_enabled = false
alert_correlation_window_minutes = 10
suppression_window_minutes = 60
escalation_enabled = false

# Metrics collection configuration
[metrics]
max_history_size = 1000
cpu_warning = 80.0
cpu_critical = 95.0
memory_warning = 85.0
memory_critical = 98.0
task_failure_rate_warning = 15.0
task_failure_rate_critical = 30.0
agent_failure_rate_warning = 10.0
agent_failure_rate_critical = 20.0
response_time_warning = 1500.0
response_time_critical = 8000.0

# Telemetry configuration
[telemetry]
max_events = 10000
enable_console_subscriber = true
enable_webhook_subscriber = false
webhook_url = ""
enable_structured_logging = true
log_level = "debug"

# Dashboard configuration
[dashboard]
theme = "light"
layout = "grid"
refresh_interval = 60
enable_real_time_updates = true
max_widgets = 15

# Log aggregation configuration (disabled in dev)
[logging]
enable_aggregation = false
aggregation_endpoint = ""
batch_size = 50
flush_interval_seconds = 60
enable_compression = false

# Tracing configuration (disabled in dev)
[tracing]
enable_distributed_tracing = false
tracing_endpoint = ""
sample_rate = 1.0
enable_error_tracing = true

# Security monitoring (basic in dev)
[security]
enable_security_monitoring = true
max_failed_login_attempts = 10
alert_on_suspicious_activity = false
enable_audit_logging = true

# Performance optimization (disabled in dev)
[performance]
enable_auto_optimization = false
optimization_interval_minutes = 120
enable_resource_pooling = true
max_connection_pool_size = 50

# Backup and recovery (simplified in dev)
[backup]
enable_automated_backups = false
backup_interval_hours = 168  # weekly
backup_retention_days = 7
enable_point_in_time_recovery = false