# Staging Monitoring Configuration
# Pre-production monitoring setup for staging environment

[production_monitoring]
# Health monitoring settings
health_check_interval_seconds = 45
performance_collection_interval_seconds = 20
metrics_retention_hours = 72  # 3 days
alert_evaluation_interval_seconds = 90
dashboard_refresh_interval_seconds = 45

# Prometheus exporter settings
enable_prometheus_exporter = true
prometheus_port = 9092

# Grafana integration
enable_grafana_integration = true
grafana_url = "http://grafana.staging.local:3000"

# Notification channels
[[production_monitoring.notification_channels]]
channel_type = "console"
enabled = true
severity_filter = ["info", "warning", "critical"]

[[production_monitoring.notification_channels]]
channel_type = "webhook"
endpoint = "https://hooks.slack.com/services/YOUR/STAGING/SLACK/WEBHOOK"
enabled = true
severity_filter = ["warning", "critical"]

# Alerting thresholds (between dev and prod)
[production_monitoring.alerting_thresholds]
agent_health_critical_threshold = 0.4
agent_health_warning_threshold = 0.6
system_cpu_critical = 92.0
system_cpu_warning = 78.0
system_memory_critical = 96.0
system_memory_warning = 82.0
task_failure_rate_critical = 30.0
task_failure_rate_warning = 12.0
response_time_critical_ms = 6000.0
response_time_warning_ms = 1200.0
error_rate_critical_per_minute = 12.0
error_rate_warning_per_minute = 3.0
agent_utilization_low_threshold = 25.0
throughput_drop_threshold_percent = 25.0

# Business metrics configuration
[production_monitoring.business_metrics_config]
enable_business_metrics = true
task_completion_target_percentage = 93.0
agent_utilization_target_percentage = 75.0
system_uptime_target_percentage = 99.5
customer_satisfaction_target_score = 4.3

# Intelligent alerting configuration
[intelligent_alerting]
max_alert_history = 5000
adaptive_learning_enabled = true
predictive_alerting_enabled = false
alert_correlation_window_minutes = 7
suppression_window_minutes = 45
escalation_enabled = true

# Metrics collection configuration
[metrics]
max_history_size = 5000
cpu_warning = 75.0
cpu_critical = 92.0
memory_warning = 82.0
memory_critical = 96.0
task_failure_rate_warning = 12.0
task_failure_rate_critical = 30.0
agent_failure_rate_warning = 7.0
agent_failure_rate_critical = 17.0
response_time_warning = 1200.0
response_time_critical = 6000.0

# Telemetry configuration
[telemetry]
max_events = 25000
enable_console_subscriber = true
enable_webhook_subscriber = true
webhook_url = "https://api.honeycomb.io/1/events/ai-orchestrator-staging"
enable_structured_logging = true
log_level = "info"

# Dashboard configuration
[dashboard]
theme = "dark"
layout = "grid"
refresh_interval = 45
enable_real_time_updates = true
max_widgets = 18

# Log aggregation configuration
[logging]
enable_aggregation = true
aggregation_endpoint = "https://logs.staging.local/api/v1/logs"
batch_size = 75
flush_interval_seconds = 45
enable_compression = true

# Tracing configuration
[tracing]
enable_distributed_tracing = true
tracing_endpoint = "https://tracing.staging.local/api/v1/spans"
sample_rate = 0.5
enable_error_tracing = true

# Security monitoring
[security]
enable_security_monitoring = true
max_failed_login_attempts = 7
alert_on_suspicious_activity = true
enable_audit_logging = true

# Performance optimization
[performance]
enable_auto_optimization = true
optimization_interval_minutes = 90
enable_resource_pooling = true
max_connection_pool_size = 75

# Backup and recovery
[backup]
enable_automated_backups = true
backup_interval_hours = 12
backup_retention_days = 14
enable_point_in_time_recovery = true