# Rustfmt Configuration - Rust Code Formatting
# This file configures rustfmt for consistent code style

# === BASIC FORMATTING ===
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# === IMPORTS ===
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# === FUNCTION FORMATTING ===
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# === EXPRESSIONS ===
overflow_delimited_expr = true
combine_control_expr = true
struct_field_align_threshold = 0

# === COMMENTS AND DOCUMENTATION ===
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
comment_width = 80

# === STRINGS AND LITERALS ===
format_strings = true
format_macro_matchers = true

# === TRAILING ELEMENTS ===
trailing_comma = "Vertical"
trailing_semicolon = true

# === WHITESPACE ===
remove_nested_parens = true
use_small_heuristics = "Default"
newline_style = "Unix"

# === ADVANCED OPTIONS ===
unstable_features = false
version = "Two"

# === SPECIFIC FORMATTING RULES ===
# Use field init shorthand when possible
use_field_init_shorthand = true

# Force explicit types when beneficial
force_explicit_abi = true

# Normalize doc attributes
normalize_doc_attributes = true

# Format generated code
format_generated_files = true

# === MACRO FORMATTING ===
macro_delimiters = "Brackets"

# === MATCH EXPRESSIONS ===
match_block_trailing_comma = false
match_arm_blocks = true

# === WHERE CLAUSES ===
where_single_line = false
force_multiline_blocks = false

# === MISCELLANEOUS ===
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false