# Rustfmt Configuration - Stable Features Only
# This file configures rustfmt for consistent code style using only stable features

# === BASIC FORMATTING ===
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# === IMPORTS ===
reorder_imports = true

# === FUNCTION FORMATTING ===
fn_params_layout = "Tall"

# === TRAILING ELEMENTS ===
# trailing_comma = "Vertical"  # Unstable feature - commented out

# === WHITESPACE ===
remove_nested_parens = true
